#ifndef PDGENUMS_H_
#define PDGENUMS_H_

namespace pdg
{
  enum class RiskyDataType {
    PTR_READ,
    PTR_WRTIE,
    ARR_IDX,
    DIV_BY_ZERO,
    NUM_ARITH,
    CONTROL_VAR,
    RISKY_KERNEL_FUNC,
    OTHER
  };

  enum class EdgeType
  {
    IND_CALL,
    CONTROLDEP_CALLINV,
    CONTROLDEP_CALLRET,
    CONTROLDEP_ENTRY,
    CONTROLDEP_BR,
    CONTROLDEP_IND_BR,
    DATA_DEF_USE,
    DATA_RAW,
    DATA_DEF_USE_LOAD,
    DATA_DEF_USE_GEP,
    DATA_DEF_USE_CAST,
    DATA_DEF_USE_ARITH,
    DATA_MAY_ALIAS,
    DATA_MUST_ALIAS,
    DATA_ALIAS,
    DATA_RET,
    DATA_STORE_TO,
    DATA_EQUL_OBJ,
    PARAMETER_IN,
    PARAMETER_IN_REV,
    PARAMETER_OUT,
    PARAMETER_FIELD,
    GLOBAL_DEP,
    VAL_DEP,
    ANNO_VAR,
    ANNO_GLOBAL,
    ANNO_OTHER,
    TYPE_OTHEREDGE
  };

  enum class GraphNodeType
  {
    INST_FUNCALL,
    INST_RET,
    INST_BR,
    INST_OTHER,
    FUNC_ENTRY,
    PARAM_FORMALIN,
    PARAM_FORMALOUT,
    PARAM_ACTUALIN,
    PARAM_ACTUALOUT,
    VAR_STATICALLOCGLOBALSCOPE,
    VAR_STATICALLOCMODULESCOPE,
    VAR_STATICALLOCFUNCTIONSCOPE,
    VAR_OTHER,
    FUNC,
    ANNO_VAR,
    ANNO_GLOBAL,
    ANNO_OTHER
  };

  enum class AccessTag
  {
    DATA_READ,
    DATA_WRITE
  };

  enum class DomainTag
  {
    KERNEL_DOMAIN,
    DRIVER_DOMAIN,
    NO_DOMAIN
  };
}

#endif